### ISSUE TITLE
Phala Registry Parsing Failed

### ISSUE THREAD

**Issue by mkchungs** [colorfulnotion/xcm-global-registry#34]
Step to reproduce: 

on https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fphala.api.onfinality.io%2Fpublic-ws#/js

Code:
```
let res = await api.query.assetsRegistry.registryInfoByIds.entries()
console.log(res)
```

Errors:
```
Error: Unable to decode storage assetsRegistry.registryInfoByIds: entry 1:: createType(AssetsRegistryAssetRegistryInfo):: decodeU8aStruct: failed at 0x43410c010080ca396124000000000000… on reserveLocation (index 2/5): Option<XcmV3MultiLocation>:: decodeU8aStruct: failed at 0x0c010080ca3961240000000000000000… on interior (index 2/2): {"_enum":{"Here":"Null","X1":"XcmV3Junction","X2":"(XcmV3Junction,XcmV3Junction)","X3":"(XcmV3Junction,XcmV3Junction,XcmV3Junction)","X4":"(XcmV3Junction,XcmV3Junction,XcmV3Junction,XcmV3Junction)","X5":"(XcmV3Junction,XcmV3Junction,XcmV3Junction,XcmV3Junction,XcmV3Junction)","X6":"(XcmV3Junction,XcmV3Junction,XcmV3Junction,XcmV3Junction,XcmV3Junction,XcmV3Junction)","X7":"(XcmV3Junction,XcmV3Junction,XcmV3Junction,XcmV3Junction,XcmV3Junction,XcmV3Junction,XcmV3Junction)","X8":"(XcmV3Junction,XcmV3Junction,XcmV3Junction,XcmV3Junction,XcmV3Junction,XcmV3Junction,XcmV3Junction,XcmV3Junction)"}}:: Unable to create Enum via index 12, in Here, X1, X2, X3, X4, X5, X6, X7, X8
    at T._newType (https://polkadot.js.org/apps/modu.35d7b28670a9806f.js:50:6842)
    at T._formatStorageSetEntry (https://polkadot.js.org/apps/modu.35d7b28670a9806f.js:50:6328)
    at https://polkadot.js.org/apps/modu.35d7b28670a9806f.js:50:6069
    at r.reduce (<anonymous>)
    at T._formatStorageSet (https://polkadot.js.org/apps/modu.35d7b28670a9806f.js:50:6039)
    at https://polkadot.js.org/apps/modu.35d7b28670a9806f.js:50:5754
    at Array.map (<anonymous>)
    at T._formatOutput (https://polkadot.js.org/apps/modu.35d7b28670a9806f.js:50:5697)
    at T._formatResult (https://polkadot.js.org/apps/modu.35d7b28670a9806f.js:50:3438)
    at h (https://polkadot.js.org/apps/modu.35d7b28670a9806f.js:50:3929)
```

**Comment by mkchungs** [comment]
solved and re-enabled: https://github.com/colorfulnotion/xcm-global-registry/pull/36
